LIST P = 16F887
#include "p16f887.inc"

; CONFIG1
; __config 0xE0F2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFEFF
 __CONFIG _CONFIG2, _BOR4V_BOR21V & _WRT_OFF

CBLOCK 0X20
 adclecturaH ;almacenar la parte alta del ADC
 adclecturaL ;almacenar la parte baja del ADC
ENDC
 
 ORG 0X0000
    GOTO INICIO
    
ORG 0X0005
INICIO
    BANKSEL ANSELH
    MOVLW   0X00 ; SE COLOCAN COMO DIGITAL TODOS LOS CANALES HIGH
    MOVWF   ANSELH
    BANKSEL TRISA
    MOVLW   0XFF
    MOVWF   TRISA
    MOVLW   0X00
    MOVWF   TRISB
    BANKSEL TRISD
    MOVLW   0X00
    MOVWF   TRISD
    
    BANKSEL ANSEL
    MOVLW   0X01 ; SE COLOCA COMO ANALOGICO EL PRIMER CANAL DEL ADC
    MOVWF   ANSEL
    
    
    BANKSEL ADCON1
    MOVLW   b'00110000'
    MOVWF   ADCON1 ;JUSTIFICADO A LA IZQUIERDA // REFERENCIAS DE VREF - VREF +
    BANKSEL ADCON0
    MOVLW   0X00
    MOVWF   ADCON0 ; SELECCIONAR RELOJ FOSC/2 .... CH=AN0 ..... ADON DESACTIVADO
    
    BSF	    ADCON0, ADON ;ACTIVAMOS EL ADC
    
    
BUCLE:	
    BANKSEL ADCON0
    BSF	    ADCON0, GO_DONE ;INICIA LA CONVERSION (GO DONE SE MANDA A CERO CUANDO LA CONVERSION SE COMPLETA)
    BTFSC   ADCON0, GO_DONE ;¿ESTA COMPLETA LA CONVERSIÓN?
    GOTO    BUCLE
    BANKSEL ADRESL
    MOVF    ADRESL,W ;MOVEMOS EL RESULTADO L AL RESGISTRO DE TRABAJO 
    BANKSEL adclecturaL
    MOVWF   adclecturaL
    
    BANKSEL ADRESH
    MOVF    ADRESH,W ;MOVEMOS EL RESULTADO H AL REGISTRO DE TRABAJO 
    BANKSEL adclecturaH
    MOVWF   adclecturaH
    
    MOVF    adclecturaH, W ;cargando a registro de trabajo la parte alta
    
    BANKSEL PORTB
    MOVWF   PORTB
    
    MOVF    adclecturaL,W
    
    BANKSEL PORTD
    MOVWF   PORTD
    
    
    
    GOTO    BUCLE ;REGRESA A LA ETIQUETA DE BUCLE
    
    

	
	

;;;;;;;;;;;;;;;;;;;;;;;    
   
	
END

