LIST P = 16F887
#include "p16f887.inc"

; CONFIG1
; __config 0xE0F2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFEFF
 __CONFIG _CONFIG2, _BOR4V_BOR21V & _WRT_OFF
 
CBLOCK 0X20
 Count167us
 Count15ms
 Count1ms 
 Count100us
 Count4_1ms
 Count334us
 Count668us
 Count1s
 NIBBLE
 Ret1  
 Ret2
  

ENDC
 
CBLOCK 0X3F
 
 GUION
 RECIBIDO
 TEMPRECIBIDO
 HOME;104 ASCII CODE
 
ENDC

	
ORG 0X0000
    GOTO INICIO
    
ORG 0X0004
    GOTO INTERRUPCION_RX    
    
ORG 0X0005
INICIO

    BANKSEL ANSEL
    MOVLW   0X00
    MOVWF   ANSEL
    MOVLW   0X00
    MOVWF   ANSELH
    
    BANKSEL TRISD
    MOVLW   0X00
    MOVWF   TRISD ; SALIDAS DIGITALES
    ;MOVLW   0XFF  ;ENTRADAS DIIGTALES
    ;MOVWF   TRISC
    
    BANKSEL TRISB
    MOVLW   0X00
    MOVWF   TRISB
    
    BANKSEL PORTB
    MOVLW   0X00
    MOVWF   PORTB
    
    BANKSEL TRISA
    MOVLW   0X00
    MOVWF   TRISA
    
    BANKSEL PORTA
    MOVLW   0X00
    MOVWF   PORTA
    
    BANKSEL GUION
    MOVLW   D'47'
    MOVWF   GUION
    
    BANKSEL HOME
    MOVLW   D'104'
    MOVWF   HOME
   
    
    CALL    LCD_Init
    CALL    LCD_Clear
    
    MOVLW   'H'
    CALL    LCD_Char
    
    
    
    ;CONFIGURACION DEL MODULO EUSART PARA LA RECEPCION DE DATOS
    
    BANKSEL SPBRG
    MOVLW   D'19'  ;CONFIGURAR BAUD RATE GENERATOR PARA 9600 BAUDIOS
    MOVWF   SPBRG
    BANKSEL TXSTA
    BCF	    TXSTA,BRGH ;TRANSMISION ASINCRONA DE BAJA VELOCIDAD
    BANKSEL BAUDCTL    ;REGISTRO DE CONTROL DE LA TASA DE BAUDIOS
    BCF	    BAUDCTL,BRG16 ;SELECCION DE GENERADOR DE BAUDIOS DE 8 BITS
    BANKSEL TXSTA
    BCF	    TXSTA,SYNC ;PUERTO SERIAL ASINCRONO
    BANKSEL RCSTA
    BSF	    RCSTA,CREN ;HABILITO LA RECEPCION
    BSF	    RCSTA,SPEN ;HABILITACION DEL PUERTO SERIAL
    
    ;CONFIGURACION DE LA TRANSMISION DE DATOS
    
    BANKSEL TXSTA
    BSF	    TXSTA,TXEN ;HABILITACION DEL ENVIO
    
    ;HABILITACION DE INTERRUPCION POR EUSART
    
    BANKSEL INTCON
    BSF	    INTCON,GIE
    BSF	    INTCON,PEIE
    BANKSEL PIE1
    BSF	    PIE1,RCIE  ;HABILITO LA INTERRUPCION POR DATOS RECIBIDOS
    BANKSEL PIR1
    BCF	    PIR1,RCIF ;LIMPIA BANDERA D EINTERRUPCION DE RECEPCION DE DATOS
    

    
BUCLE:
    
    GOTO    BUCLE
    
    
INTERRUPCION_RX:
    
    
    
    BANKSEL PIR1
    BCF	    PIR1,RCIF  ;LIMPIO LA BANDERA DE RECEPCION
    BANKSEL RCREG
    MOVF    RCREG,W
    MOVWF   RECIBIDO  ;SE MUEVE A VALOR RECIBIDO
    MOVF    RECIBIDO,W
    
    
    
    CALL    LCD_Char
    
   
    BANKSEL RECIBIDO
    MOVFW   RECIBIDO
    ;
    BANKSEL TEMPRECIBIDO
    MOVWF   TEMPRECIBIDO
    ;
    BANKSEL TXREG
    MOVWF   TXREG
    
 
    CLRW
    CLRF    STATUS
    
   
    BANKSEL GUION
    MOVFW   GUION
  
    
    BANKSEL TEMPRECIBIDO
    SUBWF   TEMPRECIBIDO,0
    
    BANKSEL STATUS
    BTFSC   STATUS,Z
    CALL    LCD_Clear
    
    
    BANKSEL HOME
    MOVFW   HOME
    
    BANKSEL TEMPRECIBIDO
    SUBWF   TEMPRECIBIDO,0
    
    BANKSEL STATUS
    BTFSC   STATUS,Z
    CALL    LCD_Home
    
    
    BANKSEL TEMPRECIBIDO
    MOVFW   TEMPRECIBIDO
    
    BANKSEL PORTA  ;SHOW data received trought eusart
    CLRF    PORTA
    MOVWF   PORTA
    
    CALL    SHOW_RECIBIDO
    
    BANKSEL RCSTA
    BSF	    RCSTA,CREN ;HABILITACION DE RECEPCIOND DE DATOS
    
    
    BANKSEL PIE1
    BSF	    PIE1,RCIE ;HABILITACION DE INTERRUPCION DE RECEPCION
    BANKSEL INTCON
    BSF	    INTCON,PEIE ;HABILITA INTERRUPCIONES DE PERIFERICOS
    BSF	    INTCON,GIE ;HABILITA INTERRUPCIONES GENERALES
    
   
    
    
    
RETFIE
    
    
SHOW_RECIBIDO:
    
    CLRF    PORTB
    
    BANKSEL RECIBIDO
    MOVFW   RECIBIDO
    
    ;MOVLW   0XFF    
    BANKSEL PORTB
    MOVWF   PORTB
   
    ;CALL    Delay1_s
    ;CALL    Delay1_s
    ;CALL    Delay1_s
    ;CALL    Delay1_s
    ;CALL    Delay1_s
    ;CALL    Delay1_s
    
    ;CLRF    PORTB   
    
RETURN;
    
    
    
INCLUDE <LCD.inc>
    

	
	

;;;;;;;;;;;;;;;;;;;;;;;    
   
	
END




