LIST P = 16F887
#include "p16f887.inc"

; CONFIG1
; __config 0xE0F2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFEFF
 __CONFIG _CONFIG2, _BOR4V_BOR21V & _WRT_OFF
 
 CBLOCK 0X20
    tiempo ;tendra almacenado el valor para obtener el tiempo especifico
    contador ;tendra almacenado el valor por mostrar en la barra de LEDS
 ENDC
 
 
	
ORG 0X0000
    GOTO INICIO
    
ORG 0X0004  ;AREA DE MEMORIA DE LAS INTERRUPCIONES        
    GOTO INTERRUPCION_TIMER
    

    
ORG 0X0005
INICIO
    BANKSEL TRISB 
    MOVLW   0X00
    MOVWF   TRISB ;PUERTTO B COMO SALIDAD
    BANKSEL PORTB
    MOVLW   0X00
    MOVWF   PORTB ; SE REINICIA EL PUERTO
    BANKSEL contador
    MOVLW   0X00
    MOVWF   contador ;REINICIO EL VALOR DEL CONTADOR
    BANKSEL INTCON    ;INTERRUPT CONTROL REGISTER
    BSF     INTCON, GIE ;HABILITO INTERRUPCIONES GENERALES
    BSF	    INTCON, PEIE ;HABILITO INTERRUPCIONES DE PERIFERICOS
    BSF	    INTCON, T0IE ;HABILITO LA INTERRUPCION POR DESBORDE DE TIMER 0
    BCF     INTCON, T0IF  ;LIMPIO EL BIT BANDERA DE LA INTERRUPCION
    
    BANKSEL OPTION_REG ;OPTION REGISTER
    BCF	    OPTION_REG, T0CS ;SELECCION DE FUENTE DE RELOJ, (0 -> INTERNAL INSTRUCTION CYCLE CLOCK, 1-> TRANSITION ON T0CKI)
    BCF	    OPTION_REG, T0SE ;SOURCE EDGE SELECTED BIT 0 -> LOW  TO HIGH  1-> HIGH TO LOW
    BCF	    OPTION_REG, PSA  ;PRESCALER ASSIGNMENT (0-> TIMER 0 MODULE, 1-> WDT MODULE) 
    BSF	    OPTION_REG, PS0 ;AJUSTE DE PREESCALER 
    BSF	    OPTION_REG, PS1;AJUSTE DE PREESCALER
    BSF	    OPTION_REG, PS2;AJUSTE DE PREESCALER  1:256
    
    BANKSEL tiempo
    MOVLW   D'50'
    MOVWF   tiempo

    
BUCLE:
    
    GOTO    BUCLE
    
INTERRUPCION_TIMER:
    BANKSEL INTCON
    BCF	    INTCON, T0IF;LIMPIO BANDERA DE LA INTERRUPCION
    BANKSEL tiempo
    DECFSZ  tiempo ;decrementamos la variable tiempo, salta si es cero
    GOTO    SALIR_INT
    MOVLW   D'50'
    MOVWF   tiempo ;ajusto el valor de tiempo en 50
    INCF    contador ;incremento el valor de contador en uno
    MOVF    contador, W ;contador -> WREG
    BANKSEL PORTB
    MOVWF   PORTB
    
SALIR_INT:
    BANKSEL INTCON
    BSF	    INTCON, T0IE
    BSF	    INTCON, GIE
    BSF	    INTCON, PEIE
    RETFIE
    
    END




