LIST P = 16F887
#include "p16f887.inc"

; CONFIG1
; __config 0xE0F2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFEFF
 __CONFIG _CONFIG2, _BOR4V_BOR21V & _WRT_OFF

 CBLOCK 0X20
   recibido
 ENDC
	
ORG 0X0000
    GOTO INICIO

ORG 0X0004
    GOTO INTERRUPCION_RX
    
ORG 0X0005
INICIO
    BANKSEL ANSEL
    MOVLW   0X00
    MOVWF   ANSEL
    MOVLW   0X00
    MOVWF   ANSELH
    
    BANKSEL TRISD
    MOVLW   0X00
    MOVWF   TRISD ; SALIDAS DIGITALES
    MOVLW   0XFF  ;ENTRADAS DIIGTALES
    MOVWF   TRISC
    
    CALL    LCD_Init
    MOVLW   0X00
    CALL    LCD_GoTo
    MOVLW   'H'
    CALL    LCD_Char
    MOVLW   'O'
    CALL    LCD_Char
    MOVLW   'L'
    CALL    LCD_Char
    MOVLW   'A'
    CALL    LCD_Char
    MOVLW   0X40
    CALL    LCD_GoTo
    
    ;CONFIGURACION DEL MODULO EUSART PARA RECEPCIÓN DE DATOS
    
    BANKSEL SPBRG  
    MOVLW   D'19'
    MOVWF   SPBRG   ;CONFIGURACON A 9600 BAUDIOS
    BANKSEL TXSTA
    BCF	    TXSTA, BRGH ;TRANSMISION ASINCRONA DE BAJA VELOCIDAD
    BANKSEL BAUDCTL   ;REGISTRO DE CONTROL DE LA TASA DE BAUDIOS
    BCF	    BAUDCTL, BRG16 ; SELECCION DE GENERADOR DE BAUDIOS DE 8 BITS
    BANKSEL TXSTA
    BCF	    TXSTA, SYNC ;PUERTO SERIAL ASINCRONO
    BANKSEL RCSTA
    BSF	    RCSTA, CREN ;HABILITO LA RECEPCION
    BSF     RCSTA, SPEN ;HABILITACION DEL PUERTO SERIAL
    
    ;CONFIGURACION DE LA TRANSMISION DE DATOS
    BANKSEL TXSTA
    BSF	    TXSTA, TXEN ; HABILITACION DEL ENVIO 
    
    ;HABILITACION DE INTERRUPCION POR EUSART
    
    BANKSEL INTCON
    BSF	    INTCON, GIE
    BSF	    INTCON, PEIE
    BANKSEL PIE1
    BSF	    PIE1, RCIE ;HABILITO LA INTERRUPCION
    BANKSEL PIR1
    BCF     PIR1, RCIF ;LIMPIO LA BANDERA
    
    
    
  
    
BUCLE:
    
    GOTO    BUCLE
    
    
INTERRUPCION_RX:
    BANKSEL PIR1
    BCF     PIR1, RCIF  ;LIMPIA LA BANDERA DE RECEPCION
    BANKSEL RCREG
    MOVF    RCREG, W
    MOVWF   recibido  ;SE MUEVE EL VALOR A RECIBIDO
    MOVF    recibido, W
    BANKSEL TXREG
    MOVWF   TXREG    ;ENVIO DEL DATO
    BANKSEL RCSTA
    BSF	    RCSTA, CREN  ;HABILITA LA RECEPCION DE DATOS
    MOVF    recibido, W
    CALL    LCD_Char
    BANKSEL PIE1
    BSF	    PIE1, RCIE  ;HABILITACION INTERRUPCION DE RECEPCION
    BANKSEL INTCON    ;
    BSF	    INTCON, GIE  ;HABILITA INTERRUPCIONES GENERALES
    BSF     INTCON, PEIE ;HABILITA INTERRUPCIONES DE PERIFERICOS
    
    RETFIE
    
    
    
    
INCLUDE <LCD_lib.inc>
    
    
    
    
;;;;;;;;;;;;;;;;;;;;;;;    
   
	
END




