LIST P = 16F887
#include "p16f887.inc"

; CONFIG1
; __config 0xE0F2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFEFF
 __CONFIG _CONFIG2, _BOR4V_BOR21V & _WRT_OFF
 
 CBLOCK	    0x20
    contador
 ENDC

	
ORG 0X0000
    GOTO INICIO
    
ORG 0x0004
    GOTO INTERRUPCION_EXTERNA
    
ORG 0X0005
INICIO
    BANKSEL ANSELH
    MOVLW   0X00
    MOVWF   ANSELH
    MOVLW   0X00
    MOVWF   ANSEL
    BANKSEL TRISB
    MOVLW   0XFF
    MOVWF   TRISB ;ENTRADA PARA LA SEÑAL DE INTERRUPCION EXTERNAS
    MOVLW   0X00
    MOVWF   TRISD ;SALIDA PARA MODULO DE LEDS
    
    BANKSEL contador
    MOVLW   0X00
    MOVWF   contador ;inicializacion del contador en cero
    
    BANKSEL INTCON
    BSF	    INTCON, GIE ;ACTIVACION DE INTERRUPCIONES GENERALES
    BSF	    INTCON, PEIE ;ACTIVACION DE LAS INTERRUPCIONES DE PERFIERICOS
    BSF	    INTCON, INTE ;HABILITACION DE INTERRUPCIONES EXTERNAS
    BCF     INTCON, INTF ;LIMPIA LA BANDERA DE LA INTERRUPCION
    
    BANKSEL OPTION_REG
    BSF	    OPTION_REG,INTEDG ;CHANGE IN RISING EDGE
    
    
    
    

    
BUCLE:
    
    GOTO    BUCLE
    
    
    
INTERRUPCION_EXTERNA:
    
    BANKSEL INTCON
    BCF	    INTCON, INTF
    BANKSEL contador
    INCF    contador
    MOVF    contador,W
    BANKSEL PORTD
    MOVWF   PORTD
    BANKSEL INTCON
    BSF	    INTCON, INTE
    BSF	    INTCON, GIE
    BSF	    INTCON, PEIE
    
    RETFIE
    
    
    END
    

	
	

;;;;;;;;;;;;;;;;;;;;;;;    
   
	
END




